# Generated by Django 6.0.3 on 2026-03-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-issue__created_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="issuetype",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="resolution",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="issue",
            name="resolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="issues.resolution",
            ),
        ),
    ]
