# Generated by Django 6.0.3 on 2026-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_alter_comment_options_alter_issue_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
